# Disable sudo to speed up the build
sudo: false

language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov
install:
  - python3 setup.py install
  - pip install ".[test]" . # install package + test dependencies
script: pytest --cov=./ # run tests
after_success:
  - codecov # submit coverage