language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov
  - sudo apt-get install python3-dev gcc libaec-dev
install:
  - python setup.py install
  - pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install ".[test]" . # install package + test dependencies
script: pytest -p pytest_cov --cov # run tests
after_success:
  - codecov # submit coverage